### ISSUE TITLE
use github.io for better navigation of this?

### ISSUE THREAD

**Issue by dimpase** [mikecroucher/SMC_tutorial#19]
Currently one can read the .md files here on github.com, but it's far from ideal.
Should it be made into a proper web-hosted doc (eg using github.io ?)

**Comment by mikecroucher** [comment]
Yes. We'll get on to it.

**Comment by mikecroucher** [comment]
Done, thanks to @trallard 
URL is https://mikecroucher.github.io/SMC_tutorial/
