### ISSUE TITLE
Adding students

### ISSUE THREAD

**Issue by IanHawke** [mikecroucher/SMC_tutorial#3]
Typing in a list of student emails to set up the course could take time. Maybe link to an aside on auto-generating such a list from eg an Excel spreadsheet (which is how I'd probably have to get the information)?

**Comment by willfurnass** [comment]
Using a Jupyter Notebook within SMC might be the easiest way to do this.  Here, a simple python solution could be:

``` python
import pandas as pd

df = pd.read_excel('students.xlsx', sheetname='details', header=0)
print(df.['email'].str.cat(sep=' '))
```

**Comment by zimmermant** [comment]
If you have the emails in an Excel file you can copy and paste the list into the 'Add Student' box

**Comment by mikecroucher** [comment]
Can confirm, zimmermant is correct.

I had a list of email addresses in an Excel spreadsheet. Copied and pasted them straight in. Probably worth mentioning this somewhere in the notes.

**Comment by trallard** [comment]
Added in PR #28
