### ISSUE TITLE
SageMathCloud → CoCalc

### ISSUE THREAD

**Issue by haraldschilly** [mikecroucher/SMC_tutorial#38]
This weekend we switched the branding. So, this tutorial is no longer correct. I don't know how you really want to proceed: 

Should I send you a pull request, do you want to hand this name change off to someone, are there other dependencies I'm not aware of? 

Also, more general, what's the long-term plan of this tutorial? Should the company behind cocalc (sagemath, inc.) at some point take over this repository? Or a fork?

**Comment by mikecroucher** [comment]
Hi Harald

I think that the way to proceed is to transfer ownership of this repo to you guys.
Do you agree @trallard ?

Cheers,
Mike

**Comment by trallard** [comment]
I think this would be the best approach as well


Best, 
Tania

**Comment by mikecroucher** [comment]
@haraldschilly Do you guys have an organisation you'd like us to transfer ownership to?

**Comment by haraldschilly** [comment]
yes, it's https://github.com/sagemathinc/ i.e. with `sagemathinc` with "inc" in the end

**Comment by mikecroucher** [comment]
No problem. I just tried to do it but don't have permission to add repos to your organisation so the transfer failed.

**Comment by haraldschilly** [comment]
oh, of course, can you please add `@haraldschilly` as a collab here to this project? 

It's probably this page: https://github.com/mikecroucher/SMC_tutorial/settings/collaboration

Then I hope I should be able to take care of everything

**Comment by mikecroucher** [comment]
Done

**Comment by haraldschilly** [comment]
Ok, I am sorry, but Github is apparently too complex. Seems like we have to transfer ownership. So, please go to settings -> transfer ownership. Then add **me** as the owner: `haraldschilly`.

**Comment by mikecroucher** [comment]
done

**Comment by haraldschilly** [comment]
Thank you, finally it worked!

**Comment by haraldschilly** [comment]
Ok, there is now https://tutorial.cocalc.com/ but I haven't figure out how to recompile it to work with that domain. Anyways, important first step is done!

**Comment by haraldschilly** [comment]
Ok, closing this ticket, we also have to come up with a proper attribution page!

https://tutorial.cocalc.com/
