### ISSUE TITLE
peer grading enhancements and auto grading

### ISSUE THREAD

**Issue by StuartLittlefair** [mikecroucher/SMC_tutorial#9]
Peer grading is fantastic! It would be even better if there were some way of allowing students to enter numerical grades and for these grades to be automatically collected and associated with the submission.

Another enhancement that would be fantastic (but I imagine much harder) is to implement a auto-grading scheme along the lines of @jhamrick 's nbgrader (https://github.com/jupyter/nbgrader). This works by creating notebook cells that contain assignments and other cells which run tests of the assignment code.  Scores are assigned to the test cells. If the tests pass without raising an exception, the score is awarded.

**Comment by haraldschilly** [comment]
Hello, enhancements to cocalc are tracked in cocalc's issue tracker. E.g. https://github.com/sagemathinc/cocalc/issues/1929

Henece I'm closing this issue.
